GET https://fullstackopenpart3.vikyw.repl.co/api/persons

###
DELETE https://fullstackopenpart3.vikyw.repl.co/api/persons/2

###
POST https://fullstackopenpart3.vikyw.repl.co/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "081234001700"
}
