GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/6359057e3f695812d56e4dc9
###
GET http://localhost:3001/info
###
DELETE http://localhost:3001/api/persons/6359057e3f695812d56e4dc9

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "as",
    "number": "081234001700"
}

###
PUT http://localhost:3001/api/persons/6359057e3f695812d56e4dc9
content-type: application/json

{
    "name": "asasa",
    "number": "081234001700"
}
